[package]
name = "netui"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.28.0"
# eframe = "0.12"
console_engine = "1.5.1"
